### ISSUE TITLE
"www.google.com" is not accessible in my country

### ISSUE THREAD

**Issue by tomatofrommars** [triologygmbh/reCAPTCHA-V2-java#3]
"www.recaptcha.net" support needed.
> Can I use reCAPTCHA globally?
https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

**Comment by schnatterer** [comment]
Did you try to change [this line](https://github.com/triologygmbh/reCAPTCHA-V2-java/blob/cc71ae7d7e4705f12c896f5a0860a42bb8da7b65/src/main/java/de/triology/recaptchav2java/ReCaptchaEndPoint.java#L38)?

**Comment by tomatofrommars** [comment]
Yes, i did. It works.

**Comment by schnatterer** [comment]
Does `www.recaptcha.net` work globally? 
If so, please create a PR, I will release a new version.

**Comment by tomatofrommars** [comment]
Yes, it does. I will send a PR.
